version: '3'
services:
  webapi:
    build: .
    ports:
      - "5000:5000"
      - "5001:5001"
    environment:
      - ASPNETCORE_HTTP_PORT=https://+:5001
      - ASPNETCORE_URLS=http://+:5000
      - ConexaoPadrao=Server=db,1433; Database=tech_test_payment_api_db; User=SA; Password=SenhaSuperSegura@123; TrustServerCertificate=true
    depends_on:
      - db
    entrypoint: [ "/bin/sh" , "-c", "dotnet /app/tech-test-payment-api.dll"]
    restart: always
    container_name: webapi
  db:
    container_name: tech_test_payment_api_db
    image: mcr.microsoft.com/mssql/server:2019-CU8-ubuntu-16.04
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=SenhaSuperSegura@123
  